#!/usr/bin/env bash
rofi \
	-show drun \
	-modi run,drun,ssh \
	-scroll-method 0 \
	-drun-match-fields all \
	-no-drun-show-actions \
	-terminal alacritty \
	-kb-cancel Alt-F1 \
	-theme "$HOME"/.config/awesome/rofi/design.rasi